from __future__ import annotations

import re
from collections import Counter, defaultdict
from typing import Final

_MIN_PATTERN_OCCURRENCES: Final = 5  # Mínimo de dominios para generar regex
_MIN_PATTERN_LENGTH: Final = 4  # Longitud mínima del patrón base


def _extract_subdomain_patterns(domains: set[str]) -> dict[str, list[str]]:
    """Extrae patrones de subdominios agrupados por dominio base.

    Ejemplo: ad1.example.com, ad2.example.com -> example.com: [ad1, ad2]
    """
    base_to_subdomains: dict[str, list[str]] = defaultdict(list)

    for domain in domains:
        parts = domain.split(".")
        if len(parts) < 3:
            continue

        # Tomar los últimos 2 segmentos como base
        base = ".".join(parts[-2:])
        subdomain = ".".join(parts[:-2])
        base_to_subdomains[base].append(subdomain)

    return base_to_subdomains


def _find_numeric_patterns(subdomains: list[str]) -> list[str]:
    """Detecta patrones numéricos en subdominios.

    Ejemplo: ad1, ad2, ad3 -> ad[0-9]+
    """
    patterns = []
    prefix_counts: Counter[str] = Counter()

    for sub in subdomains:
        # Buscar prefijo seguido de números
        match = re.match(r"^([a-z]+)(\d+)$", sub)
        if match:
            prefix_counts[match.group(1)] += 1

    for prefix, count in prefix_counts.items():
        if count >= _MIN_PATTERN_OCCURRENCES and len(prefix) >= _MIN_PATTERN_LENGTH:
            patterns.append(f"{prefix}[0-9]+")

    return patterns


def _find_tracking_patterns(subdomains: list[str]) -> list[str]:
    """Detecta patrones comunes de tracking.

    Ejemplo: tracking, tracker, track-1 -> track
    """
    patterns = []
    tracking_keywords = ["track", "pixel", "beacon", "metric", "analytic", "stat", "click", "log"]

    for keyword in tracking_keywords:
        matches = [s for s in subdomains if keyword in s.lower()]
        if len(matches) >= _MIN_PATTERN_OCCURRENCES:
            patterns.append(f".*{keyword}.*")

    return patterns


def generate_regex_patterns(domains: set[str]) -> list[str]:
    """Genera patrones regex optimizados para Pi-hole.

    Analiza los dominios y genera regex que cubren múltiples dominios
    con patrones similares.

    Args:
        domains: Set de dominios.

    Returns:
        Lista de patrones regex en formato Pi-hole.
    """
    base_to_subdomains = _extract_subdomain_patterns(domains)
    regex_patterns: list[str] = []

    for base, subdomains in base_to_subdomains.items():
        if len(subdomains) < _MIN_PATTERN_OCCURRENCES:
            continue

        # Detectar patrones numéricos
        numeric_patterns = _find_numeric_patterns(subdomains)
        for pattern in numeric_patterns:
            # Formato Pi-hole: (\\.|^)pattern\\.base$
            escaped_base = re.escape(base)
            regex_patterns.append(f"(\\.|^){pattern}\\.{escaped_base}$")

        # Detectar patrones de tracking
        tracking_patterns = _find_tracking_patterns(subdomains)
        for pattern in tracking_patterns:
            escaped_base = re.escape(base)
            regex_patterns.append(f"(\\.|^){pattern}\\.{escaped_base}$")

    # Eliminar duplicados y ordenar
    return sorted(set(regex_patterns))


def write_regex_file(output_path, patterns: list[str]) -> int:
    """Escribe archivo de regex para Pi-hole.

    Args:
        output_path: Path de salida.
        patterns: Lista de patrones regex.

    Returns:
        Número de patrones escritos.
    """
    if not patterns:
        return 0

    header = [
        "# Pi-hole Regex Blocklist",
        "# Generated by blocklist-factory",
        "# Add these patterns in Pi-hole: Domains > Add domain (Regex)",
        "#",
        "# Each pattern blocks multiple domains matching the pattern.",
        "#",
    ]
    content = "\n".join(header) + "\n" + "\n".join(patterns) + "\n"
    output_path.write_text(content, encoding="utf-8")

    return len(patterns)
